CREATE TABLE recipe(
    recipe_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    recipe_name TEXT NOT NULL,
    unit_weight NUMERIC
(8,2), 
    flour_total NUMERIC
(8,2), 
    flours JSON NOT NULL, 
    ingredients JSON NOT NULL
);
